# import numpy as np
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 400
WINDOW_CAPTION = "Happy Days"
# VIEWPORT = np.array([WINDOW_WIDTH, WINDOW_HEIGHT])

PLAYER_MAX_VELOCITY = 1

ENEMY_ON_SPAWN_MIN_DIST = 1.5

EPSILON = 0.000001

# ======== HUD ======
HP_BAR_WIDTH = 150
HP_BAR_HEIGHT = 20
HP_BAR_XPOS = WINDOW_WIDTH - HP_BAR_WIDTH - 10
HP_BAR_YPOS = 10

